import {
  Product,
  ProductCategory,
  ProductReview,
  Coupon,
  ShippingMethod,
  Address,
  Order,
  AdminStats,
  User,
  VariantGroup,
  VariantOption,
} from '../types';

export const INITIAL_USER: User = {
  id: 'usr-default-1',
  name: 'Alex Rivera',
  firstName: 'Alex',
  lastName: 'Rivera',
  email: 'alex.rivera@aura-studio.com',
  phone: '+1 (415) 882-9011',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'customer',
  createdAt: '2025-01-15T10:00:00Z',
  isEmailVerified: true,
};

export const ADMIN_USER: User = {
  id: 'usr-admin-1',
  name: 'Elena Vance',
  firstName: 'Elena',
  lastName: 'Vance',
  email: 'admin@aura-studio.com',
  phone: '+1 (415) 555-0199',
  avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  role: 'admin',
  createdAt: '2024-11-01T08:00:00Z',
  isEmailVerified: true,
};

export const CATEGORIES: ProductCategory[] = [
  {
    id: 'cat-all',
    name: 'All Products',
    slug: 'all',
    description: 'Explore our complete collection of refined lifestyle goods.',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    productCount: 18,
  },
  {
    id: 'cat-audio',
    name: 'Acoustics & Sound',
    slug: 'audio',
    description: 'Minimalist studio-grade audio crafted for discerning listeners.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    productCount: 5,
  },
  {
    id: 'cat-workspace',
    name: 'Workspace & Tech',
    slug: 'workspace',
    description: 'Ergonomic tools and desktop monoliths to elevate your daily focus.',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80',
    productCount: 4,
  },
  {
    id: 'cat-living',
    name: 'Living & Interior',
    slug: 'living',
    description: 'Sculptural lighting, organic ceramics, and timeless home accents.',
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80',
    productCount: 3,
  },
  {
    id: 'cat-carry',
    name: 'Bags & EDC',
    slug: 'carry',
    description: 'Durable weather-resistant carry goods for modern nomadism.',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    productCount: 3,
  },
  {
    id: 'cat-apparel',
    name: 'Apparel & Wear',
    slug: 'apparel',
    description: 'Architectural silhouettes, fine merino wool, and functional daily shirts.',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    productCount: 3,
  },
];

export const BRANDS = [
  'AURA Studio',
  'Nomad Atelier',
  'Kanso Craft',
  'Vanguard Goods',
  'Horizon Sound',
  'Stilform Labs',
];

const RAW_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'AURA Pulse Wireless Headphones',
    slug: 'aura-pulse-wireless-headphones',
    tagline: 'Active noise cancellation with 40mm beryllium drivers.',
    description: 'Engineered from machined aircraft aluminum and supple vegan leather. AURA Pulse delivers studio-fidelity acoustic reproduction with responsive hybrid active noise cancellation and 36-hour battery endurance.',
    price: 349.00,
    originalPrice: 399.00,
    category: 'audio',
    brand: 'AURA Studio',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 18,
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isNew: true,
    tags: ['Best Seller', 'ANC', 'Wireless'],
    features: [
      'Custom 40mm Beryllium acoustic transducers',
      'Adaptive Hybrid Noise Cancellation with transparency pass-through',
      'Bluetooth 5.3 with LDAC, aptX Adaptive and multipoint pairing',
      '38 hours total playback with quick 10-minute fast charge',
      'Dual beamforming array microphones for crystal voice clarity',
    ],
    dimensions: '190 × 170 × 80 mm',
    material: 'Machined Anodized Aluminum, Memory Foam, Protein Leather',
    colors: [
      { name: 'Obsidian Black', hex: '#1c1917' },
      { name: 'Silver Ash', hex: '#e2e8f0' },
      { name: 'Nordic Sage', hex: '#84a98c' },
    ],
  },
  {
    id: 'prod-2',
    name: 'Nomad Anodized Desk Lamp',
    slug: 'nomad-anodized-desk-lamp',
    tagline: 'Architectural LED illumination with capacitive touch dial.',
    description: 'Precision-extruded from solid aluminum alloy with an integrated 98+ CRI LED module that reduces optical fatigue. Features stepless rotary brightness dimming and 3 calibrated color temperature modes.',
    price: 185.00,
    originalPrice: 220.00,
    category: 'workspace',
    brand: 'Nomad Atelier',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 12,
    rating: 4.8,
    reviewCount: 29,
    isFeatured: true,
    tags: ['Design Award', 'Workspace'],
    features: [
      'Ultra-high 98+ CRI for accurate color perception',
      'Capacitive touch brass control dial with stepless dimming',
      'Heavy cast base with non-slip micro-suction pad',
      'Built-in 15W Qi wireless charging tray on base',
    ],
    dimensions: '420 × 120 × 380 mm',
    material: 'Anodized 6063 Aluminum, Brass Accent, Polycarbonate Diffuser',
    colors: [
      { name: 'Space Gray', hex: '#334155' },
      { name: 'Brushed Brass', hex: '#d4af37' },
      { name: 'Pure Chalk', hex: '#f8fafc' },
    ],
  },
  {
    id: 'prod-3',
    name: 'Kanso Stoneware Ceramic Vessel',
    slug: 'kanso-stoneware-ceramic-vessel',
    tagline: 'Hand-thrown sculptural vase with textured matte reactive glaze.',
    description: 'Rooted in minimalist wabi-sabi philosophy, each vessel is wheel-thrown in small artisanal batches using mineral-rich stoneware clay. Beautiful as a standalone silhouette or filled with dried botanicals.',
    price: 95.00,
    category: 'living',
    brand: 'Kanso Craft',
    images: [
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 9,
    rating: 4.7,
    reviewCount: 16,
    isFeatured: false,
    tags: ['Handmade', 'Ceramics'],
    features: [
      'Wheel-thrown mineral stoneware fired at 1280°C',
      'Matte volcanic reactive glaze with natural earthy speckling',
      '100% watertight interior with glazed seal',
      'Felt-lined base to protect delicate tabletop finishes',
    ],
    dimensions: '220 × 140 mm',
    material: 'Stoneware Clay, Volcanic Ash Glaze',
    colors: [
      { name: 'Warm Pumice', hex: '#d6d3d1' },
      { name: 'Terracotta Soil', hex: '#9a3412' },
      { name: 'Charcoal Basalt', hex: '#292524' },
    ],
  },
  {
    id: 'prod-4',
    name: 'Vanguard Technical Roll-Top Backpack',
    slug: 'vanguard-technical-roll-top-backpack',
    tagline: 'Cordura 500D weatherproof commuter pack with Fidlock magnet closures.',
    description: 'Designed for the urban cyclist and remote creative. Built with water-repellent Cordura Ballistic nylon, magnetic German Fidlock buckles, and an independent suspended 16-inch laptop compartment.',
    price: 220.00,
    originalPrice: 260.00,
    category: 'carry',
    brand: 'Vanguard Goods',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 15,
    rating: 4.9,
    reviewCount: 54,
    isFeatured: true,
    isNew: true,
    tags: ['Weatherproof', 'Commuter'],
    features: [
      '500D Cordura® nylon exterior with TPU water-repellent coating',
      'German-engineered Fidlock V-buckles for rapid one-handed latching',
      'Suspended EVA foam padded pocket fits up to 16” MacBook Pro',
      'Hidden passport and AirTag stash pockets against lumbar backpanel',
      '24-liter expandable volume with reinforced luggage passthrough',
    ],
    dimensions: '480 × 300 × 160 mm',
    material: 'Cordura 500D, YKK Aquaguard Zippers, Hypalon Pulls',
    colors: [
      { name: 'Matte Stealth Black', hex: '#0f172a' },
      { name: 'Deep Forest', hex: '#14532d' },
    ],
  },
  {
    id: 'prod-5',
    name: 'Acoustic Sound Bar Horizon',
    slug: 'acoustic-sound-bar-horizon',
    tagline: 'Solid walnut wooden acoustic soundbar with AirPlay 2 and Spotify Connect.',
    description: 'Combines Scandinavian organic aesthetics with cutting-edge DSP amplification. Acoustic fabric wraps a solid American walnut chassis harboring 6 independent drivers and dual passive radiators.',
    price: 495.00,
    category: 'audio',
    brand: 'Horizon Sound',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1543512214-318c7553f230?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 6,
    rating: 4.9,
    reviewCount: 38,
    isFeatured: true,
    tags: ['Audiophile', 'Smart Home'],
    features: [
      '120W Class-D digital amplification with dual DSP engines',
      'Solid CNC-machined American Walnut cabinet for acoustic warmth',
      'Apple AirPlay 2, Google Cast, Spotify Connect & HDMI eARC',
      'Acoustically transparent Danish wool blend fabric',
    ],
    dimensions: '650 × 110 × 90 mm',
    material: 'Solid Walnut Wood, Kvadrat Wool Fabric, Steel',
    colors: [
      { name: 'Natural Walnut', hex: '#5c4033' },
      { name: 'Smoked Oak', hex: '#3e2723' },
    ],
  },
  {
    id: 'prod-6',
    name: 'MagStand CNC Solid MagSafe Dock',
    slug: 'magstand-cnc-solid-magsafe-dock',
    tagline: 'Precision weighted charging stand milled from a single brass billet.',
    description: 'Weighing over 1.2 lbs, the MagStand stays grounded when you lift your phone. Compatible with all MagSafe and Qi2 devices with micro-suction anti-slip footing.',
    price: 78.00,
    category: 'workspace',
    brand: 'Nomad Atelier',
    images: [
      'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1616353071855-2c045c4458ae?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 25,
    rating: 4.6,
    reviewCount: 19,
    isFeatured: false,
    tags: ['Workspace', 'MagSafe'],
    features: [
      'Heavy 550g solid alloy counterweight prevents tip-over',
      'Optimal 60-degree viewing angle for FaceTime & StandBy mode',
      'Silicone gasket protects device edges from scratches',
      'Braided 2-meter USB-C cable included',
    ],
    dimensions: '110 × 85 × 115 mm',
    material: 'Billet Aluminum / Brass, Japanese Micro-suction',
    colors: [
      { name: 'Space Gray', hex: '#475569' },
      { name: 'Silver Mist', hex: '#cbd5e1' },
      { name: 'Raw Brass', hex: '#ca8a04' },
    ],
  },
  {
    id: 'prod-7',
    name: 'Merino Wool Minimalist Throw',
    slug: 'merino-wool-minimalist-throw',
    tagline: 'Extra-fine 19.5-micron Australian merino wool woven blanket.',
    description: 'Incredibly soft and naturally thermoregulating. Jacquard-woven with subtle geometric relief and finished with hand-knotted eyelash fringes.',
    price: 165.00,
    category: 'living',
    brand: 'Kanso Craft',
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1606744824163-985d376605aa?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 8,
    rating: 4.8,
    reviewCount: 22,
    isFeatured: false,
    tags: ['Cozy', 'Natural Fiber'],
    features: [
      '100% ethically sourced Australian Merino wool (19.5 micron)',
      'Breathable, moisture-wicking and naturally odor-resistant',
      'OEKO-TEX® Standard 100 certified, free from harsh chemical dyes',
      'Generous 140 × 190 cm dimensions',
    ],
    dimensions: '140 × 190 cm',
    material: '100% Virgin Merino Wool',
    colors: [
      { name: 'Oatmeal Heather', hex: '#e7e5e4' },
      { name: 'Olive Moss', hex: '#4d5b41' },
      { name: 'Deep Indigo', hex: '#1e293b' },
    ],
  },
  {
    id: 'prod-8',
    name: 'AURA Scribe Titanium Mechanical Pencil',
    slug: 'aura-scribe-titanium-pencil',
    tagline: 'Grade 5 titanium writing instrument with internal brass clutch.',
    description: 'Balanced with precision weight distribution at the lower third for effortless sketching and note-taking. Features a zero-play Japanese brass mechanism with 0.5mm lead.',
    price: 88.00,
    category: 'workspace',
    brand: 'AURA Studio',
    images: [
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1585336261026-77884d5dfce6?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 30,
    rating: 4.9,
    reviewCount: 31,
    isFeatured: false,
    tags: ['Titanium', 'EDC'],
    features: [
      'Solid Grade 5 Titanium body (Ti-6Al-4V)',
      'Micro-grooved grip section machined with 0.1mm tolerances',
      'Heavy-duty hardened stainless steel clip',
      'Includes refill tube with 30 high-purity polymer 2B leads',
    ],
    dimensions: '142 × 9 mm (28g)',
    material: 'Grade 5 Titanium, C3604 Brass',
    colors: [
      { name: 'Stonewashed Gray', hex: '#64748b' },
      { name: 'DLC Midnight Black', hex: '#0f172a' },
    ],
  },
  {
    id: 'prod-9',
    name: 'AURA Heavyweight Merino Studio Shirt',
    slug: 'aura-heavyweight-merino-studio-shirt',
    tagline: 'Thermoregulating 280gsm merino wool overshirt with corozo buttons.',
    description: 'Cut from dense 280gsm New Zealand merino wool that resists wrinkles and regulates body heat through changing climates. Features internal passport chest pocket and natural corozo nut buttons.',
    price: 135.00,
    originalPrice: 165.00,
    category: 'apparel',
    brand: 'AURA Studio',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 16,
    rating: 4.9,
    reviewCount: 28,
    isFeatured: true,
    isNew: true,
    tags: ['shirt', 'merino', 'apparel', 'men', 'best-seller'],
    features: [
      '280gsm ultrafine merino wool',
      'Naturally antibacterial and odor-resistant',
      'Internal hidden chest zippered pocket',
      'Reinforced elbow articulation for durable work wear',
    ],
    dimensions: 'Sizes XS – XXL',
    material: '100% Merino Wool, Corozo Nut',
    colors: [
      { name: 'Oatmeal Taupe', hex: '#d1c7bd' },
      { name: 'Midnight Charcoal', hex: '#1e293b' },
    ],
  },
  {
    id: 'prod-10',
    name: 'Nomad Technical Overshirt Jacket',
    slug: 'nomad-technical-overshirt-jacket',
    tagline: 'Water-resistant stretch-woven utility shirt with dual cargo pockets.',
    description: 'Engineered for seamless transition from workspace to transit. DWR-coated four-way stretch nylon resists sudden showers and abrasions while providing unrestricted movement.',
    price: 180.00,
    category: 'apparel',
    brand: 'Nomad Atelier',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 11,
    rating: 4.7,
    reviewCount: 19,
    tags: ['shirt', 'overshirt', 'apparel', 'men', 'weatherproof'],
    features: [
      'Four-way stretch technical twill with DWR water-shedding finish',
      'Dual concealed magnetic flap chest pockets',
      'YKK matte black metal snap fasteners',
      'Articulated sleeves tailored for mobility',
    ],
    dimensions: 'Sizes S – XL',
    material: '88% Recycled Nylon, 12% Spandex',
    colors: [
      { name: 'Matte Olive', hex: '#3f4f38' },
      { name: 'Stealth Black', hex: '#0f172a' },
    ],
  },
  {
    id: 'prod-11',
    name: 'Vanguard Minimalist Everyday Oxford Shirt',
    slug: 'vanguard-minimalist-everyday-oxford-shirt',
    tagline: 'Structured organic cotton oxford with hidden button-down collar.',
    description: 'A timeless tailored essential crafted from certified organic long-staple cotton with clean hidden plackets and taped seam longevity.',
    price: 85.00,
    originalPrice: 105.00,
    category: 'apparel',
    brand: 'Vanguard Goods',
    images: [
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1620012253295-c15c429fcc7e?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 22,
    rating: 4.8,
    reviewCount: 35,
    tags: ['shirt', 'oxford', 'men', 'organic'],
    features: [
      'Certified 100% GOTS organic combed cotton',
      'Hidden under-collar button lock for clean lapel stance',
      'Curved hem designed for tucked or untucked wear',
      'Pre-washed to eliminate post-wash shrinkage',
    ],
    dimensions: 'Sizes XS – XXL',
    material: '100% Organic Cotton',
    colors: [
      { name: 'Crisp White', hex: '#ffffff' },
      { name: 'Sky Blue', hex: '#93c5fd' },
    ],
  },
  {
    id: 'prod-12',
    name: 'Stilform Precision Ballpoint Pen',
    slug: 'stilform-precision-ballpoint-pen',
    tagline: 'Magnetic cap retraction mechanism machined from solid aerospace brass.',
    description: 'The worlds first magnetic ballpoint pen engineered with neodymium magnets. Emits an audible mechanical snap on cap engage and accepts standard G2 refills.',
    price: 65.00,
    category: 'workspace',
    brand: 'Stilform Labs',
    images: [
      'https://images.unsplash.com/photo-1585336261026-77884d5dfce6?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 14,
    rating: 4.6,
    reviewCount: 12,
    tags: ['EDC', 'Stationery', 'Brass'],
    features: [
      'Patented magnetic sliding mechanism',
      'Anti-roll chamfered hex body design',
      'Schmidt P900M German black ink cartridge included',
    ],
    dimensions: '137 × 9.5 mm (45g)',
    material: 'Solid Brass C360',
    colors: [
      { name: 'Warm Brass', hex: '#d4af37' },
      { name: 'Rose Gold', hex: '#b76e79' },
    ],
  },
  {
    id: 'prod-13',
    name: 'Horizon True Wireless Studio Earbuds',
    slug: 'horizon-true-wireless-studio-earbuds',
    tagline: 'Carbon composite diaphragm with spatial head-tracking and Qi case.',
    description: 'Ultra-low distortion micro-drivers housed in ceramic sound chambers with 8-hour standalone playback and 32 hours via aluminum charging capsule.',
    price: 199.00,
    originalPrice: 249.00,
    category: 'audio',
    brand: 'Horizon Sound',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: false,
    stockCount: 0,
    rating: 4.7,
    reviewCount: 24,
    isNew: true,
    tags: ['Earbuds', 'Wireless', 'ANC'],
    features: [
      '11mm graphene composite drivers with aptX Lossless support',
      'IPX5 sweat and weather resistance',
      'Wireless Qi charging case milled from aircraft aluminum',
    ],
    dimensions: '60 × 42 × 24 mm case',
    material: 'Zirconia Ceramic, Anodized Aluminum',
    colors: [
      { name: 'Piano White', hex: '#f8fafc' },
      { name: 'Gloss Black', hex: '#0f172a' },
    ],
  },
  {
    id: 'prod-14',
    name: 'Kanso Matte Black Pour-Over Kettle',
    slug: 'kanso-matte-black-pour-over-kettle',
    tagline: 'Balanced gooseneck spout with built-in analog thermometer dial.',
    description: 'Precision flow control for pour-over coffee rituals. 304 food-grade stainless steel coated in heat-resistant matte powder coat with solid walnut handle.',
    price: 115.00,
    category: 'living',
    brand: 'Kanso Craft',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 7,
    rating: 4.8,
    reviewCount: 18,
    tags: ['Coffee', 'Kitchen', 'Living'],
    features: [
      'Counterbalanced ergonomic solid walnut handle',
      'Fluted gooseneck spout engineered for slow 90-degree laminar water pour',
      'Integrated analog temperature brew gauge on lid',
    ],
    dimensions: '290 × 140 × 160 mm (1.0L capacity)',
    material: '304 Stainless Steel, Walnut Wood',
    colors: [
      { name: 'Matte Charcoal', hex: '#262626' },
    ],
  },
  {
    id: 'prod-15',
    name: 'Vanguard Modular Tech Pouch',
    slug: 'vanguard-modular-tech-pouch',
    tagline: 'Weatherproof origami-folding cables, charger and hard drive organizer.',
    description: 'Stands upright on your desk. Origami accordion interior expands to hold power bricks, cables, pens, and memory cards without bulk.',
    price: 55.00,
    category: 'carry',
    brand: 'Vanguard Goods',
    images: [
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 28,
    rating: 4.5,
    reviewCount: 15,
    tags: ['EDC', 'Organizer', 'Tech'],
    features: [
      'Weather-resistant 420D ripstop nylon shell with water-sealed zipper',
      'Accordion structure keeps small accessories organized and visible',
      'Dedicated zippered passport & SD card sub-compartment',
    ],
    dimensions: '240 × 150 × 100 mm',
    material: '420D Nylon Ripstop, Hypalon',
    colors: [
      { name: 'Graphite', hex: '#4b5563' },
      { name: 'Slate Blue', hex: '#3b82f6' },
    ],
  },
  {
    id: 'prod-16',
    name: 'AURA Studio Acoustic Reference Monitors',
    slug: 'aura-studio-acoustic-reference-monitors',
    tagline: 'Active bi-amped studio monitors with Kevlar cones and ribbon tweeters.',
    description: 'Pristine nearfield acoustic precision for audio engineers and music purists. Features balanced XLR inputs, optical digital, and custom room tuning calibration.',
    price: 580.00,
    originalPrice: 650.00,
    category: 'audio',
    brand: 'AURA Studio',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 4,
    rating: 5.0,
    reviewCount: 11,
    isFeatured: true,
    tags: ['Audiophile', 'Studio', 'Speakers'],
    features: [
      '5.25-inch woven Kevlar low-frequency transducers',
      'Air Motion Transformer (AMT) ribbon high-frequency tweeter',
      '150W total RMS Class-AB bi-amplification per pair',
      'Acoustic space tuning controls for corner and wall placement',
    ],
    dimensions: '280 × 180 × 220 mm each',
    material: 'High-Density MDF, Acoustic Wool, Anodized Baffle',
    colors: [
      { name: 'Matte Black', hex: '#171717' },
      { name: 'Arctic Birch', hex: '#e2e8f0' },
    ],
  },
  {
    id: 'prod-17',
    name: 'Nomad Solid Walnut Monitor Riser',
    slug: 'nomad-solid-walnut-monitor-riser',
    tagline: 'Ergonomic solid hardwood shelf with integrated aluminum cable track.',
    description: 'Crafted from sustainable American Black Walnut with satin oil wax finish. Raises screens to ergonomic eye level while storing full-sized keyboards below.',
    price: 140.00,
    category: 'workspace',
    brand: 'Nomad Atelier',
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 9,
    rating: 4.8,
    reviewCount: 21,
    tags: ['Workspace', 'Wood', 'Ergonomic'],
    features: [
      'Solid FSC-certified American Black Walnut slab',
      'Natural food-safe matte hardwax oil treatment',
      'Integrated brushed aluminum hidden cable route trench',
      'Holds displays up to 45kg (100 lbs) without deflection',
    ],
    dimensions: '1050 × 230 × 115 mm',
    material: 'Solid American Walnut, Anodized 6061 Aluminum',
    colors: [
      { name: 'Natural Walnut', hex: '#5c4033' },
    ],
  },
  {
    id: 'prod-18',
    name: 'Kanso Minimalist Concrete Desk Planter',
    slug: 'kanso-minimalist-concrete-desk-planter',
    tagline: 'Architectural cast concrete pot with hidden drainage reservoir.',
    description: 'Poured by hand using ultra-dense polymer-modified architectural cement. Includes water catchment saucer for succulents and desk greenery.',
    price: 45.00,
    category: 'living',
    brand: 'Kanso Craft',
    images: [
      'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=900&auto=format&fit=crop&q=80',
    ],
    inStock: true,
    stockCount: 19,
    rating: 4.6,
    reviewCount: 14,
    tags: ['Botanical', 'Decor', 'Concrete'],
    features: [
      'Hand-cast architectural concrete with breathable pores',
      'Integrated hidden drip tray with protective cork bottom pad',
      'Naturally alkaline porous walls prevent root rot',
    ],
    dimensions: '120 × 120 × 100 mm',
    material: 'Cast Architectural Cement, Natural Cork',
    colors: [
      { name: 'Raw Light Gray', hex: '#94a3b8' },
      { name: 'Graphite Dark', hex: '#334155' },
    ],
  },
];

function enrichProduct(p: Product): Product {
  const isOutOfStock = !p.inStock || p.stockCount === 0;

  // 1. Color Variant Group
  const colorOptions: VariantOption[] = (p.colors && p.colors.length > 0)
    ? p.colors.map((c, i) => ({
        id: `col-${i}-${c.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
        name: c.name,
        value: c.name,
        colorHex: c.hex,
        image: p.images?.[i] || p.images?.[0],
        inStock: isOutOfStock ? false : (i === 2 ? false : true), // 3rd color disabled/out of stock for demo
        stockCount: isOutOfStock ? 0 : (i === 2 ? 0 : Math.max(2, (p.stockCount || 12) - i * 3)),
      }))
    : [
        {
          id: 'col-default',
          name: 'Signature Finish',
          value: 'Signature Finish',
          colorHex: '#1c1917',
          image: p.images?.[0],
          inStock: !isOutOfStock,
          stockCount: p.stockCount || 10,
        },
      ];

  // 2. Size / Form Factor Variant Group
  const sizeOptions: VariantOption[] = [
    {
      id: 'size-standard',
      name: p.category === 'carry' ? '20L Daily' : p.category === 'workspace' ? 'Standard' : 'Studio Over-Ear',
      value: 'standard',
      inStock: !isOutOfStock,
      stockCount: isOutOfStock ? 0 : Math.max(1, p.stockCount || 10),
      priceOffset: 0,
    },
    {
      id: 'size-extended',
      name: p.category === 'carry' ? '28L Travel (+ $35)' : p.category === 'workspace' ? 'Extended Pro (+ $25)' : 'Memory Foam XL (+ $25)',
      value: 'extended',
      inStock: !isOutOfStock,
      stockCount: isOutOfStock ? 0 : Math.max(1, Math.floor((p.stockCount || 10) / 2)),
      priceOffset: p.category === 'carry' ? 35.00 : 25.00,
    },
  ];

  // 3. Material Variant Group
  const materialOptions: VariantOption[] = [
    {
      id: 'mat-core',
      name: p.material?.split(',')?.[0]?.trim() || 'Matte Aerospace Alloy',
      value: 'core',
      inStock: !isOutOfStock,
      stockCount: isOutOfStock ? 0 : (p.stockCount || 10),
      priceOffset: 0,
    },
    {
      id: 'mat-premium',
      name: p.category === 'audio' ? 'Perforated Nappa Leather (+ $45)' : 'Hand-Brushed Brass Accents (+ $45)',
      value: 'premium',
      inStock: !isOutOfStock,
      stockCount: isOutOfStock ? 0 : Math.max(1, Math.floor((p.stockCount || 10) / 3)),
      priceOffset: 45.00,
    },
  ];

  // 4. Custom Edition Group
  const editionOptions: VariantOption[] = [
    {
      id: 'ed-standard',
      name: 'Standard Studio Packaging',
      value: 'standard',
      inStock: !isOutOfStock,
      stockCount: isOutOfStock ? 0 : (p.stockCount || 10),
      priceOffset: 0,
    },
    {
      id: 'ed-collectors',
      name: "Collector's Monograph Box (+ $65)",
      value: 'collectors',
      inStock: !isOutOfStock,
      stockCount: isOutOfStock ? 0 : 3,
      priceOffset: 65.00,
    },
  ];

  const variantGroups: VariantGroup[] = [
    {
      id: 'group-color',
      name: 'Color Finish',
      type: 'color',
      required: true,
      options: colorOptions,
    },
    {
      id: 'group-size',
      name: 'Form & Sizing',
      type: 'size',
      required: false,
      options: sizeOptions,
    },
    {
      id: 'group-material',
      name: 'Material Grade',
      type: 'material',
      required: false,
      options: materialOptions,
    },
    {
      id: 'group-edition',
      name: 'Packaging Edition',
      type: 'custom',
      required: false,
      options: editionOptions,
    },
  ];

  const specifications: Record<string, string> = {
    'Dimensions': p.dimensions || '210 × 170 × 60 mm',
    'Primary Materials': p.material || 'Anodized 6061 Aluminum, Stainless Steel',
    'Studio Brand': p.brand || 'AURA Studio',
    'Origin & Engineering': 'Designed in San Francisco, Engineered in California',
    'Hardware Guarantee': '2-Year Limited Studio Guarantee (parts & labor)',
    'Acoustic / Precision Tuning': p.category === 'audio' ? 'Beryllium Transducers with Dual Resonant Chambers' : 'Precision CNC Machined Tolerances (0.01mm)',
    'Interface & Connectivity': p.category === 'audio' ? 'Bluetooth 5.3 (aptX Lossless, LDAC), 3.5mm Analog Audio' : 'Standard USB-C High-Speed Interface',
    'What Is In The Box': 'Device, Braided Armored Cable, Microfiber Cloth, Calibration Certificate',
    'Environmental Compliance': 'Carbon-neutral certified, 100% plastic-free recycled pulp packaging',
  };

  return {
    ...p,
    variants: p.variants || variantGroups,
    specifications: p.specifications || specifications,
    shippingInfo: p.shippingInfo || 'Complimentary carbon-neutral standard delivery on orders over $150. Orders before 2:00 PM PST ship same day.',
    returnPolicy: p.returnPolicy || '30-Day risk-free trial. Enjoy complimentary return postage with full refund in original packaging.',
    warranty: p.warranty || '2-Year Comprehensive Studio Guarantee against manufacturing and material flaws.',
  };
}

export const INITIAL_PRODUCTS: Product[] = RAW_PRODUCTS.map(enrichProduct);

export const INITIAL_REVIEWS: ProductReview[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userId: 'usr-10',
    userName: 'Marcus Thorne',
    userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'The acoustic balance is truly sublime',
    comment: 'I compose film scores and have used dozens of monitor pairs. The AURA Pulse creates an extraordinarily wide soundstage without bloated bass. The noise cancellation doesn’t generate any pressure sensation.',
    verifiedPurchase: true,
    createdAt: '2025-08-14T14:32:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    userId: 'usr-11',
    userName: 'Sophia Lindqvist',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Worth every penny for long haul flights',
    comment: 'Took these from Tokyo to Stockholm. Comfortable through 14 hours straight, and the battery still had 60% left upon arrival.',
    verifiedPurchase: true,
    createdAt: '2025-08-28T09:15:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-2',
    userId: 'usr-12',
    userName: 'Julian Vance',
    userAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'The brass dial feels so satisfying',
    comment: 'The build quality is reminiscent of vintage Leica gear. The light temperature presets are tuned gracefully for evening desk sessions.',
    verifiedPurchase: true,
    createdAt: '2025-09-02T19:40:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-4',
    userId: 'usr-13',
    userName: 'Camila Rodriguez',
    userAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    rating: 5,
    title: 'Kept my laptop dry in torrential rain',
    comment: 'Got caught in a severe thunderstorm in Seattle while cycling. Opened the pack expecting moisture, but the inside was bone dry. Fidlock buckles are addicting.',
    verifiedPurchase: true,
    createdAt: '2025-09-10T11:20:00Z',
  },
];

export const COUPONS: Coupon[] = [
  {
    code: 'AURA15',
    discountPercent: 15,
    description: '15% off any order over $100',
    minSpend: 100,
  },
  {
    code: 'WELCOME25',
    discountAmount: 25,
    description: '$25 off orders above $150',
    minSpend: 150,
  },
  {
    code: 'STUDIO20',
    discountPercent: 20,
    description: '20% off for studio members',
    minSpend: 200,
  },
];

export const SHIPPING_METHODS: ShippingMethod[] = [
  {
    id: 'ship-standard',
    name: 'Standard Carbon-Neutral',
    description: 'Delivered by electric courier fleet',
    price: 0,
    estimatedDays: '3–5 business days',
  },
  {
    id: 'ship-express',
    name: 'Priority Air Express',
    description: 'Real-time GPS tracking & insurance',
    price: 15.00,
    estimatedDays: '1–2 business days',
  },
  {
    id: 'ship-overnight',
    name: 'Signature Overnight',
    description: 'Guaranteed delivery before noon',
    price: 28.00,
    estimatedDays: 'Next business day by 12:00 PM',
  },
];

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    userId: 'usr-default-1',
    fullName: 'Alex Rivera',
    street: '742 Evergreen Terrace',
    apartment: 'Loft 4B',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94107',
    country: 'United States',
    phone: '+1 (415) 882-9011',
    type: 'both',
    isDefaultShipping: true,
    isDefaultBilling: true,
  },
  {
    id: 'addr-2',
    userId: 'usr-default-1',
    fullName: 'Alex Rivera (Design Studio)',
    street: '180 Townsend Street',
    apartment: 'Floor 3',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94103',
    country: 'United States',
    phone: '+1 (415) 555-0199',
    type: 'shipping',
    isDefaultShipping: false,
    isDefaultBilling: false,
  },
  {
    id: 'addr-3',
    userId: 'usr-default-1',
    fullName: 'Alex Rivera (Accounting)',
    street: '55 2nd Street',
    apartment: 'Suite 1200',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94105',
    country: 'United States',
    phone: '+1 (415) 882-9011',
    type: 'billing',
    isDefaultShipping: false,
    isDefaultBilling: false,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-84920',
    orderNumber: 'ORD-84920',
    userId: 'usr-default-1',
    items: [
      {
        productId: 'prod-1',
        productName: 'AURA Pulse Wireless Headphones',
        productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&auto=format&fit=crop&q=80',
        price: 349.00,
        quantity: 1,
        selectedColor: 'Obsidian Black',
      },
      {
        productId: 'prod-6',
        productName: 'MagStand CNC Solid MagSafe Dock',
        productImage: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=900&auto=format&fit=crop&q=80',
        price: 78.00,
        quantity: 1,
        selectedColor: 'Space Gray',
      },
    ],
    shippingAddress: INITIAL_ADDRESSES[0],
    billingAddress: INITIAL_ADDRESSES[0],
    shippingMethod: SHIPPING_METHODS[0],
    paymentMethod: {
      type: 'card',
      brand: 'Visa',
      last4: '4242',
    },
    paymentStatus: 'paid',
    fulfillmentStatus: 'delivered',
    subtotal: 427.00,
    discount: 42.70,
    tax: 30.74,
    shippingCost: 0,
    total: 415.04,
    status: 'delivered',
    couponApplied: {
      code: 'WELCOME10',
      discountPercent: 10,
      description: '10% Welcome discount',
    },
    trackingNumber: 'AUR-992817420-US',
    carrier: 'FedEx Express Carbon-Neutral',
    estimatedDeliveryDate: '2025-08-14T11:00:00Z',
    createdAt: '2025-08-10T16:20:00Z',
    updatedAt: '2025-08-14T11:00:00Z',
  },
  {
    id: 'ORD-91204',
    orderNumber: 'ORD-91204',
    userId: 'usr-default-1',
    items: [
      {
        productId: 'prod-2',
        productName: 'Nomad Anodized Desk Lamp',
        productImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900&auto=format&fit=crop&q=80',
        price: 185.00,
        quantity: 1,
        selectedColor: 'Brushed Brass',
      },
    ],
    shippingAddress: INITIAL_ADDRESSES[0],
    billingAddress: INITIAL_ADDRESSES[0],
    shippingMethod: SHIPPING_METHODS[1],
    paymentMethod: {
      type: 'apple_pay',
    },
    paymentStatus: 'paid',
    fulfillmentStatus: 'processing',
    subtotal: 185.00,
    discount: 0,
    tax: 14.80,
    shippingCost: 15.00,
    total: 214.80,
    status: 'processing',
    trackingNumber: 'AUR-449102830-US',
    carrier: 'DHL Express Worldwide',
    estimatedDeliveryDate: '2025-09-22T17:00:00Z',
    createdAt: '2025-09-18T10:30:00Z',
    updatedAt: '2025-09-19T08:12:00Z',
  },
  {
    id: 'ORD-94511',
    orderNumber: 'ORD-94511',
    userId: 'usr-default-1',
    items: [
      {
        productId: 'prod-4',
        productName: 'Vanguard Technical Roll-Top Backpack',
        productImage: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900&auto=format&fit=crop&q=80',
        price: 220.00,
        quantity: 1,
        selectedColor: 'Matte Stealth Black',
      },
      {
        productId: 'prod-15',
        productName: 'Vanguard Modular Tech Pouch',
        productImage: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=900&auto=format&fit=crop&q=80',
        price: 55.00,
        quantity: 2,
        selectedColor: 'Graphite',
      },
    ],
    shippingAddress: INITIAL_ADDRESSES[1],
    billingAddress: INITIAL_ADDRESSES[0],
    shippingMethod: SHIPPING_METHODS[2],
    paymentMethod: {
      type: 'card',
      brand: 'Mastercard',
      last4: '8821',
    },
    paymentStatus: 'paid',
    fulfillmentStatus: 'shipped',
    subtotal: 330.00,
    discount: 25.00,
    tax: 24.40,
    shippingCost: 28.00,
    total: 357.40,
    status: 'shipped',
    couponApplied: {
      code: 'STUDIO25',
      discountAmount: 25,
      description: 'Studio Member Voucher',
    },
    trackingNumber: 'AUR-881290341-US',
    carrier: 'UPS Next Day Air',
    estimatedDeliveryDate: '2025-09-26T12:00:00Z',
    createdAt: '2025-09-24T09:15:00Z',
    updatedAt: '2025-09-24T14:40:00Z',
  },
];

export const INITIAL_ADMIN_STATS: AdminStats = {
  totalRevenue: 54920.00,
  totalOrders: 284,
  totalProducts: 8,
  activeCustomers: 1840,
  recentSales: [
    { date: 'Mon', amount: 3420 },
    { date: 'Tue', amount: 4890 },
    { date: 'Wed', amount: 3120 },
    { date: 'Thu', amount: 6200 },
    { date: 'Fri', amount: 7400 },
    { date: 'Sat', amount: 8900 },
    { date: 'Sun', amount: 6800 },
  ],
  topSellingProducts: [
    { id: 'prod-1', name: 'AURA Pulse Wireless Headphones', unitsSold: 94, revenue: 32806 },
    { id: 'prod-4', name: 'Vanguard Technical Roll-Top Backpack', unitsSold: 62, revenue: 13640 },
    { id: 'prod-2', name: 'Nomad Anodized Desk Lamp', unitsSold: 41, revenue: 7585 },
    { id: 'prod-6', name: 'MagStand CNC Solid MagSafe Dock', unitsSold: 58, revenue: 4524 },
  ],
};
